#!/usr/bin/env python3

from sys import argv
import os
import re

fp = open(argv[1], 'w')
filelist = {}

def writeline(line):
  global fp
  fp.write(line + "\n")

def writeasmline(line):
  writeline(line + "\\n\\")

writeline('// generated by AM')
writeline('#include <stdint.h>')
writeline('#include <stdio.h>')
writeline('')
writeline('asm ("\\')
writeasmline('.section .rodata.disk, \\"a\\"')
fp_filelist = open(argv[2], 'r')
while True:
  filepath = fp_filelist.readline().strip()
  if not filepath:
    break
  varname = re.sub(r'\W', '_', filepath)
  writeasmline('.global __am_%s' % varname)
  writeasmline('__am_%s:' % varname)
  writeasmline('.incbin \\"%s\\"' % filepath)
  writeasmline('.byte 0')
  filelist[filepath] = varname

writeline('");')

writeline('')
for f in filelist:
  varname = filelist[f]
  writeline('extern uint8_t __am_%s;' % varname)

writeline('')
writeline('struct file {')
writeline('  const char *name;')
writeline('  uint8_t *base;')
writeline('  uint32_t size;')
writeline('};')
writeline('static struct file filelist [] = {')
for f in filelist:
  varname = filelist[f]
  writeline('  { .name = "%s", .base = &__am_%s, .size = %d },' % (f, varname, os.path.getsize(f)))

writeline('  { .name = NULL, .base = NULL, .size = 0 }')
writeline('};')
writeline('struct file *__am_filelist = filelist;')

